steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/portfolio-app:$COMMIT_SHA", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/portfolio-app:$COMMIT_SHA"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "gsantoshkumar-in" # Use the exact service name that appears in your logs
      - "--image"
      - "gcr.io/$PROJECT_ID/portfolio-app:$COMMIT_SHA"
      - "--region"
      - "asia-south1" # Changed to match your region
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--min-instances"
      - "1"
      - "--max-instances"
      - "5"
      - "--cpu"
      - "1"
      - "--memory"
      - "1Gi"
      - "--timeout"
      - "300s"
      - "--session-affinity"
      - "--startup-cpu-boost"
      - "--cpu-throttling"
      - "--set-env-vars=NODE_ENV=production,HOST=0.0.0.0,HOSTNAME=0.0.0.0"
      - "--container-command=npm"
      - "--container-arg=start"

images:
  - "gcr.io/$PROJECT_ID/portfolio-app:$COMMIT_SHA"

timeout: "1200s"
